 
- id: doi:10.1016/j.arrct.2021.100174
  # author/date/publisher/etc filled in automatically by Manubot


- id: doi:10.3389/fpsyg.2020.00486

# author/date/publisher/etc filled in automatically by Manubot

- id: doi:10.3389/fpsyg.2020.00180
# author/date/publisher/etc filled in automatically by Manubot


- id: doi:10.1007/s11192-018-2706-x
# author/date/publisher/etc filled in automatically by Manubot


- id: doi:10.3389/fpsyg.2016.00708
# author/date/publisher/etc filled in automatically by Manubot


- id: doi:10.3389/fpsyg.2013.00628
# author/date/publisher/etc filled in automatically by Manubot

- id: doi:10.3389/fnins.2012.00107
# author/date/publisher/etc filled in automatically by Manubot


- id: doi:10.1080/10790268.2022.2052503
# author/date/publisher/etc filled in automatically by Manubot

-id: doi:10.4103/ijoy.ijoy_12_22

-id: doi:10.1038/s41394-022-00542-6

-id: doi:10.1080/10790268.2022.2052503

-id: doi: 10.1016/j.tine.2022.100172

